module.exports = {
  1: {
    id: 1,
    name: 'product 1',
    description: 'product description 1',
    price: 1.23,
    quantity: 42,
  },
  2: {
    id: 2,
    name: 'product 2',
    description: 'product description 2',
    price: 1.23,
    quantity: 42,
  },
  3: {
    id: 3,
    name: 'product 3',
    description: 'product description 3',
    price: 1.23,
    quantity: 42,
  },
  4: {
    id: 4,
    name: 'product 4',
    description: 'product description 4',
    price: 1.23,
    quantity: 42,
  },
  5: {
    id: 5,
    name: 'product 5',
    description: 'product description 5',
    price: 1.23,
    quantity: 42,
  },
  6: {
    id: 6,
    name: 'product 6',
    description: 'product description 6',
    price: 1.23,
    quantity: 42,
  },
  7: {
    id: 7,
    name: 'product 7',
    description: 'product description 7',
    price: 1.23,
    quantity: 42,
  },
  8: {
    id: 8,
    name: 'product 8',
    description: 'product description 8',
    price: 1.23,
    quantity: 42,
  },
  9: {
    id: 9,
    name: 'product 9',
    description: 'product description 9',
    price: 1.23,
    quantity: 42,
  },
  10: {
    id: 10,
    name: 'product 10',
    description: 'product description 10',
    price: 1.23,
    quantity: 42,
  },
  11: {
    id: 11,
    name: 'product 11',
    description: 'product description 11',
    price: 1.23,
    quantity: 42,
  },
  12: {
    id: 12,
    name: 'product 12',
    description: 'product description 12',
    price: 1.23,
    quantity: 42,
  },
  13: {
    id: 13,
    name: 'product 13',
    description: 'product description 13',
    price: 1.23,
    quantity: 42,
  },
  14: {
    id: 14,
    name: 'product 14',
    description: 'product description 14',
    price: 1.23,
    quantity: 42,
  },
  15: {
    id: 15,
    name: 'product 15',
    description: 'product description 15',
    price: 1.23,
    quantity: 42,
  },
  16: {
    id: 16,
    name: 'product 16',
    description: 'product description 16',
    price: 1.23,
    quantity: 42,
  },
  17: {
    id: 17,
    name: 'product 17',
    description: 'product description 17',
    price: 1.23,
    quantity: 42,
  },
  18: {
    id: 18,
    name: 'product 18',
    description: 'product description 18',
    price: 1.23,
    quantity: 42,
  },
  19: {
    id: 19,
    name: 'product 19',
    description: 'product description 19',
    price: 1.23,
    quantity: 42,
  },
  20: {
    id: 20,
    name: 'product 20',
    description: 'product description 20',
    price: 1.23,
    quantity: 42,
  },
  21: {
    id: 21,
    name: 'product 21',
    description: 'product description 21',
    price: 1.23,
    quantity: 42,
  },
  22: {
    id: 22,
    name: 'product 22',
    description: 'product description 22',
    price: 1.23,
    quantity: 42,
  },
  23: {
    id: 23,
    name: 'product 23',
    description: 'product description 23',
    price: 1.23,
    quantity: 42,
  },
  24: {
    id: 24,
    name: 'product 24',
    description: 'product description 24',
    price: 1.23,
    quantity: 42,
  },
  25: {
    id: 25,
    name: 'product 25',
    description: 'product description 25',
    price: 1.23,
    quantity: 42,
  },
  26: {
    id: 26,
    name: 'product 26',
    description: 'product description 26',
    price: 1.23,
    quantity: 42,
  },
  27: {
    id: 27,
    name: 'product 27',
    description: 'product description 27',
    price: 1.23,
    quantity: 42,
  },
  28: {
    id: 28,
    name: 'product 28',
    description: 'product description 28',
    price: 1.23,
    quantity: 42,
  },
  29: {
    id: 29,
    name: 'product 29',
    description: 'product description 29',
    price: 1.23,
    quantity: 42,
  },
  30: {
    id: 30,
    name: 'product 30',
    description: 'product description 30',
    price: 1.23,
    quantity: 42,
  },
  31: {
    id: 31,
    name: 'product 31',
    description: 'product description 31',
    price: 1.23,
    quantity: 42,
  },
  32: {
    id: 32,
    name: 'product 32',
    description: 'product description 32',
    price: 1.23,
    quantity: 42,
  },
  33: {
    id: 33,
    name: 'product 33',
    description: 'product description 33',
    price: 1.23,
    quantity: 42,
  },
  34: {
    id: 34,
    name: 'product 34',
    description: 'product description 34',
    price: 1.23,
    quantity: 42,
  },
  35: {
    id: 35,
    name: 'product 35',
    description: 'product description 35',
    price: 1.23,
    quantity: 42,
  },
  36: {
    id: 36,
    name: 'product 36',
    description: 'product description 36',
    price: 1.23,
    quantity: 42,
  },
  37: {
    id: 37,
    name: 'product 37',
    description: 'product description 37',
    price: 1.23,
    quantity: 42,
  },
  38: {
    id: 38,
    name: 'product 38',
    description: 'product description 38',
    price: 1.23,
    quantity: 42,
  },
  39: {
    id: 39,
    name: 'product 39',
    description: 'product description 39',
    price: 1.23,
    quantity: 42,
  },
  40: {
    id: 40,
    name: 'product 40',
    description: 'product description 40',
    price: 1.23,
    quantity: 42,
  },
  41: {
    id: 41,
    name: 'product 41',
    description: 'product description 41',
    price: 1.23,
    quantity: 42,
  },
  42: {
    id: 42,
    name: 'product 42',
    description: 'product description 42',
    price: 1.23,
    quantity: 42,
  },
  43: {
    id: 43,
    name: 'product 43',
    description: 'product description 43',
    price: 1.23,
    quantity: 42,
  },
  44: {
    id: 44,
    name: 'product 44',
    description: 'product description 44',
    price: 1.23,
    quantity: 42,
  },
  45: {
    id: 45,
    name: 'product 45',
    description: 'product description 45',
    price: 1.23,
    quantity: 42,
  },
  46: {
    id: 46,
    name: 'product 46',
    description: 'product description 46',
    price: 1.23,
    quantity: 42,
  },
  47: {
    id: 47,
    name: 'product 47',
    description: 'product description 47',
    price: 1.23,
    quantity: 42,
  },
  48: {
    id: 48,
    name: 'product 48',
    description: 'product description 48',
    price: 1.23,
    quantity: 42,
  },
  49: {
    id: 49,
    name: 'product 49',
    description: 'product description 49',
    price: 1.23,
    quantity: 42,
  },
  50: {
    id: 50,
    name: 'product 50',
    description: 'product description 50',
    price: 1.23,
    quantity: 42,
  },
}
